version: '3'
services:
  db:
    container_name: db
    image: mysql
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
       - MYSQL_USER=root
       - MYSQL_ROOT_PASSWORD=abc123
       - MYSQL_DATABASE=web.wordpress
  web.wordpress:
    container_name: web.wordpress
    image: wordpress
    environment:
       - WORDPRESS_DB_HOST=db
       - WORDPRESS_DB_USER=root
       - WORDPRESS_DB_PASSWORD=abc123
       - WORDPRESS_DB_NAME=web.wordpress
    ports:
       - 80:80
    restart: always